name: automerge
on: 
  workflow_run:
    workflows: ["deps-watch"]
    types: 
      - completed
jobs:
  printactor:
    runs-on: ubuntu-latest
    steps:
      - name: print actor
        run: echo "${{ github.actor }}"
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"